/**
 * A curated allow-list of widely-used npm packages.
 *
 * This list powers slopguard's *offline* heuristics:
 *  - membership check: a package on this list is treated as established/known;
 *  - typosquat distance: names that are 1-2 edits away from a known name are
 *    suspicious;
 *  - conflation detection: hallucinated names are often two known names mashed
 *    together (e.g. "react-codeshift" from "react-codemod" + "jscodeshift").
 *
 * It is intentionally a high-signal subset, not the whole registry. In
 * --online mode the live registry is the source of truth for existence; this
 * list still drives the similarity heuristics.
 */
export const KNOWN_PACKAGES: readonly string[] = Object.freeze([
  // framework / ui
  "react",
  "react-dom",
  "react-router",
  "react-router-dom",
  "react-codemod",
  "vue",
  "vue-router",
  "svelte",
  "sveltekit",
  "next",
  "nuxt",
  "angular",
  "@angular/core",
  "preact",
  "solid-js",
  "lit",
  "ember-source",
  // build / bundlers / transpilers
  "webpack",
  "rollup",
  "vite",
  "esbuild",
  "parcel",
  "babel",
  "@babel/core",
  "typescript",
  "tsx",
  "ts-node",
  "swc",
  "@swc/core",
  "jscodeshift",
  "turbo",
  // testing
  "jest",
  "mocha",
  "chai",
  "vitest",
  "ava",
  "tape",
  "cypress",
  "playwright",
  "@playwright/test",
  "testing-library",
  "@testing-library/react",
  "supertest",
  "sinon",
  // node / server
  "express",
  "koa",
  "fastify",
  "hapi",
  "nest",
  "@nestjs/core",
  "socket.io",
  "ws",
  "axios",
  "node-fetch",
  "got",
  "undici",
  "cors",
  "helmet",
  "body-parser",
  "morgan",
  "passport",
  "jsonwebtoken",
  "bcrypt",
  "bcryptjs",
  "multer",
  "dotenv",
  "nodemon",
  "pm2",
  // data / db
  "mongoose",
  "mongodb",
  "pg",
  "mysql",
  "mysql2",
  "sqlite3",
  "better-sqlite3",
  "redis",
  "ioredis",
  "knex",
  "prisma",
  "@prisma/client",
  "sequelize",
  "typeorm",
  "drizzle-orm",
  // utility
  "lodash",
  "underscore",
  "ramda",
  "moment",
  "dayjs",
  "date-fns",
  "luxon",
  "uuid",
  "nanoid",
  "chalk",
  "commander",
  "yargs",
  "inquirer",
  "ora",
  "glob",
  "rimraf",
  "fs-extra",
  "cross-env",
  "concurrently",
  "semver",
  "minimist",
  "debug",
  "ms",
  "qs",
  "classnames",
  "clsx",
  "immer",
  "zod",
  "yup",
  "joi",
  "ajv",
  // state / data fetching
  "redux",
  "@reduxjs/toolkit",
  "react-redux",
  "mobx",
  "zustand",
  "recoil",
  "jotai",
  "react-query",
  "@tanstack/react-query",
  "@tanstack/query-core",
  "swr",
  "apollo-client",
  "@apollo/client",
  "graphql",
  "urql",
  // styling
  "styled-components",
  "emotion",
  "@emotion/react",
  "tailwindcss",
  "postcss",
  "autoprefixer",
  "sass",
  "less",
  // linting / formatting
  "eslint",
  "prettier",
  "stylelint",
  "husky",
  "lint-staged",
  // ai / ml
  "openai",
  "@anthropic-ai/sdk",
  "langchain",
  "@langchain/core",
  "ai",
  "@huggingface/inference",
  "onnxruntime-node",
  "tiktoken",
  "@google/generative-ai",
  // misc popular
  "rxjs",
  "three",
  "d3",
  "chart.js",
  "puppeteer",
  "cheerio",
  "sharp",
  "jimp",
  "pino",
  "winston",
  "node-cron",
  "bull",
  "bullmq",
  "@octokit/rest",
  "stripe",
  "aws-sdk",
  "@aws-sdk/client-s3",
  "firebase",
  "firebase-admin",
]);

/** Lower-cased set for O(1) membership checks. */
export const KNOWN_PACKAGE_SET: ReadonlySet<string> = new Set(
  KNOWN_PACKAGES.map((p) => p.toLowerCase()),
);
